site_name: 生信知识花园
site_url: https://shenweiyan.github.io/Knowledge-Garden/
site_description: '记录 Bio+IT 相关的知识，沉淀生活，记录点滴。'
docs_dir: "docs"
site_dir: "site"
extra_css: 
  - css/dark.css
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.sections
repo_url: https://github.com/shenweiyan/Knowledge-Garden/
site_author: Steven Shum
copyright: Copyright © 2021-2023 Steven Shum
nav:
    - 阅读说明: README.md
    - 技术私房菜: cookbook
    - 随笔乱弹: https://www.yuque.com/shenweiyan/mind
    - 语雀知识库: https://www.yuque.com/shenweiyan
    - RSS feed: https://shenweiyan.github.io/Knowledge-Garden/feed_rss_created.xml
markdown_extensions:
    - smarty
    - toc:
        permalink: True
        separator: "-"
        toc_depth: 3
    - pymdownx.highlight
    - fancyboxmd
plugins:
  - rss:
      enabled: True
      image: https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Feed-icon.svg/128px-Feed-icon.svg.png
      categories:
        - Cookbook
      pretty_print: True
      length: 1000
      as_creation: "date"
      as_update: "date"
      abstract_chars_count: -1
      #datetime_format: "%Y-%m-%d"
      
  - search:
      separator: '[\s\u200b\-]'
  - git-revision-date
  - include_dir_to_nav
